---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "strongdm.name" . }}
  namespace: {{ include "strongdm.namespace" . }}
  annotations:
    {{- include "strongdm.annotations" (merge (dict "addtl" .Values.strongdm.deployment.annotations) .) | nindent 4 }}
  labels:
    {{- include "strongdm.labels" (merge (dict "addtl" .Values.strongdm.deployment.labels) .) | nindent 4 }}
spec:
  replicas: {{ .Values.strongdm.deployment.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 200%
      maxUnavailable: 0%
  selector:
    matchLabels:
      {{- include "strongdm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- include "strongdm.annotations" (merge (dict "addtl" .Values.strongdm.pod.annotations) .) | nindent 8 }}
      labels:
        {{- include "strongdm.labels" (merge (dict "addtl" .Values.strongdm.pod.labels) .) | nindent 8 }}
    spec:
      restartPolicy: Always
      {{- if or .Values.strongdm.serviceAccount.create .Values.strongdm.serviceAccount.name }}
      serviceAccountName: {{ .Values.strongdm.serviceAccount.create | ternary (include "strongdm.name" .) .Values.strongdm.serviceAccount.name }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      nodeSelector:
        {{- with .Values.strongdm.deployment.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      tolerations:
        {{- with .Values.strongdm.deployment.tolerations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      topologySpreadConstraints:
        {{- range $k, $v := .Values.strongdm.deployment.topologySpreadConstraints }}
        - topologyKey: {{ $k }}
          maxSkew: {{ $v.maxSkew }}
          whenUnsatisfiable: {{ $v.whenUnsatisfiable }}
          labelSelector:
            matchLabels:
              {{- include "strongdm.selectorLabels" $ | nindent 14 }}
            {{- if semverCompare ">=1.27.0" $.Capabilities.KubeVersion.Version }}
            matchLabelKeys:
              - pod-template-hash
            {{- end }}
        {{- end }}
      {{- if .Values.strongdm.service.tlsSecretName }}
      volumes:
        - name: tls
          secret:
            secretName: {{ .Values.strongdm.service.tlsSecretName }}
      {{- end }}
      containers:
        - name: sdm
          image: {{ template "strongdm.imageURI" . }}
          imagePullPolicy: {{ .Values.strongdm.image.pullPolicy }}
          {{- include "strongdm.resources" (dict "resources" .Values.strongdm.pod.resources) | nindent 10 }}
          args: ["proxy", "-d"]
          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  containerName: sdm
                  resource: requests.cpu
                  divisor: "1"
            - name: SDM_PROXY_CLUSTER_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-secrets" (include "strongdm.name" .)) .Values.strongdm.auth.secretName }}
                  key: SDM_PROXY_CLUSTER_ACCESS_KEY
            - name: SDM_PROXY_CLUSTER_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ default (printf "%s-secrets" (include "strongdm.name" .)) .Values.strongdm.auth.secretName }}
                  key: SDM_PROXY_CLUSTER_SECRET_KEY
          envFrom:
            - configMapRef:
                name: {{ include "strongdm.name" . }}-config
          ports:
            - name: healthcheck
              containerPort: 9090
              protocol: TCP
            - name: proxy
              containerPort: {{ .Values.strongdm.service.containerPort }}
              protocol: TCP
            {{- if .Values.strongdm.config.enableMetrics }}
            - name: metrics
              containerPort: 9999
              protocol: TCP
            {{- end }}
          {{- if .Values.strongdm.service.tlsSecretName }}
          volumeMounts:
            - name: tls
              mountPath: /etc/sdm
              readOnly: true
          {{- end }}
          livenessProbe:
            httpGet:
              path: /liveness
              port: 9090
            initialDelaySeconds: 25
            timeoutSeconds: 10
            periodSeconds: 15
            failureThreshold: 5
