{{- if not .Values.strongdm.auth.secretName }}
{{- if not (or .Values.strongdm.auth.adminToken (and .Values.strongdm.auth.clusterKey .Values.strongdm.auth.clusterSecret)) }}
{{- fail "both @strongdm.auth.clusterKey and @strongdm.auth.clusterSecret must be set when @strongdm.auth.secretName is not provided." }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "strongdm.annotations" . | nindent 4 }}
  labels:
    {{- include "strongdm.labels" . | nindent 4 }}
type: Opaque
data:
  SDM_PROXY_CLUSTER_ACCESS_KEY: {{ .Values.strongdm.auth.clusterKey | b64enc }}
  SDM_PROXY_CLUSTER_SECRET_KEY: {{ .Values.strongdm.auth.clusterSecret | b64enc }}
  SDM_ADMIN_TOKEN: {{ .Values.strongdm.auth.adminToken | b64enc }}
{{- end }}
