kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-secret
  labels:
{{- include "sdm.labels" . | indent 4 }}
type: Opaque
{{- with .Values.secret }}
stringData:
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
