---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "strongdm.annotations" (merge (dict "addtl" .Values.strongdm.service.annotations) .) | nindent 4 }}
  labels:
    {{- include "strongdm.labels" (merge (dict "addtl" .Values.strongdm.service.labels) .) | nindent 4 }}
spec:
  type: {{ .Values.strongdm.service.type }}
  loadBalancerIP: {{ .Values.strongdm.service.loadBalancerIP }}
  selector:
     {{- include "strongdm.selectorLabels" . | nindent 4 }}
  ports:
    - name: sdm
      port: {{ .Values.strongdm.service.listenPort }}
      targetPort: {{ .Values.strongdm.service.containerPort }}
      nodePort: {{ .Values.strongdm.service.nodePort }}
