{{- if .Values.strongdm.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: {{ include "strongdm.name" . }}
  namespace: {{ include "strongdm.namespace" . }}
  annotations:
    {{- include "strongdm.annotations" (merge (dict "addtl" .Values.strongdm.serviceAccount.annotations) .) | nindent 4 }}
  labels:
    {{- include "strongdm.labels" (merge (dict "addtl" .Values.strongdm.serviceAccount.labels) .) | nindent 4 }}
{{- end }}
