apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "strongdm.name" . }}-config
  namespace: {{ include "strongdm.namespace" . }}
  annotations:
    {{- include "strongdm.annotations" . | nindent 4 }}
  labels:
    {{- include "strongdm.labels" . | nindent 4 }}
data:
  SDM_APP_DOMAIN: {{ include "strongdm.appDomain" . }}
  SDM_VERBOSE: {{ .Values.strongdm.config.verboseLogs | quote }}
  SDM_DISABLE_UPDATE: "true"
  {{- range $k, $v := .Values.strongdm.config.additionalEnvVars }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
