{{- if not .Values.strongdm.auth.secretName }}
{{- if not .Values.strongdm.auth.serviceToken }}
{{- fail "@strongdm.auth.serviceToken must be set when @strongdm.auth.secretName is not provided." }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "strongdm.name" . }}-secrets
  namespace: {{ include "strongdm.namespace" . }}
  annotations:
    {{- include "strongdm.annotations" . | nindent 4 }}
  labels:
    {{- include "strongdm.labels" . | nindent 4 }}
type: Opaque
data:
  SDM_SERVICE_TOKEN: {{ .Values.strongdm.auth.serviceToken | b64enc }}
{{- end }}
