apiVersion: v2
name: sdm-client
kubeVersion: '>= 1.16.0-0'
version: 1.0.2
description: StrongDM Client Container
type: application
icon: https://raw.githubusercontent.com/strongdm/charts/main/sdm_icon.png
home: https://github.com/strongdm/charts
maintainers:
  - name: StrongDM
    email: k8s+sdm@strongdm.com
sources:
  - https://github.com/strongdm/charts/tree/main/deployments/sdm-client
keywords:
  - strongdm
  - sdm
