repos:
-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.6.1
    hooks:
    -   id: pre-commit-update

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: local
    hooks:
    -   id: template-install-relay
        name: Helm template | install | relay
        entry: helm template deployments/sdm-relay -f deployments/sdm-relay/values.yaml
        language: system
        pass_filenames: false
    -   id: template-install-proxy
        name: Helm template | install | proxy
        entry: helm template deployments/sdm-proxy -f deployments/sdm-proxy/values.yaml
        language: system
        pass_filenames: false
    -   id: template-install-client
        name: Helm template | install | client
        entry: helm template deployments/sdm-client -f deployments/sdm-client/values.yaml
        language: system
        pass_filenames: false
    -   id: template-upgrade-relay
        name: Helm template | upgrade | relay
        entry: helm template deployments/sdm-relay -f deployments/sdm-relay/values.yaml --is-upgrade
        language: system
        pass_filenames: false
    -   id: template-upgrade-proxy
        name: Helm template | upgrade | proxy
        entry: helm template deployments/sdm-proxy -f deployments/sdm-proxy/values.yaml --is-upgrade
        language: system
        pass_filenames: false
    -   id: template-upgrade-client
        name: Helm template | upgrade | client
        entry: helm template deployments/sdm-client -f deployments/sdm-client/values.yaml --is-upgrade
        language: system
        pass_filenames: false

-   repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.25
    hooks:
    -   id: helmlint
    -   id: shellcheck
