repos:
-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.8.0
    hooks:
    -   id: pre-commit-update

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
    -   id: helmlint
    -   id: shellcheck

-   repo: local
    hooks:
    # Basic rendering tests
    -   id: install-relay
        name: Helm install | relay
        entry: helm install deployments/sdm-relay --dry-run=client
          --generate-name -f deployments/sdm-relay/values.test.yaml
        language: system
        pass_filenames: false
    -   id: install-gateway
        name: Helm install | gateway
        entry: helm install deployments/sdm-relay --dry-run=client
          --generate-name -f deployments/sdm-relay/values.test.yaml --set
          strongdm.gateway.enabled=true
        language: system
        pass_filenames: false
    -   id: install-proxy
        name: Helm install | proxy
        entry: helm install deployments/sdm-proxy --dry-run=client
          --generate-name -f deployments/sdm-proxy/values.test.yaml
        language: system
        pass_filenames: false
    -   id: install-client
        name: Helm install | client
        entry: helm install deployments/sdm-client --dry-run=client
          --generate-name -f deployments/sdm-client/values.test.yaml
        language: system
        pass_filenames: false
    -   id: upgrade-relay
        name: Helm upgrade | relay
        entry: /bin/bash -c 'helm template deployments/sdm-relay -f
          deployments/sdm-relay/values.test.yaml | kubectl apply
          --dry-run=client -f -'
        language: system
        pass_filenames: false
    -   id: upgrade-gateway
        name: Helm upgrade | gateway
        entry: /bin/bash -c 'helm template deployments/sdm-relay -f
          deployments/sdm-relay/values.test.yaml --set
          strongdm.gateway.enabled=true | kubectl apply --dry-run=client -f -'
        language: system
        pass_filenames: false
    -   id: upgrade-proxy
        name: Helm upgrade | proxy
        entry: /bin/bash -c 'helm template deployments/sdm-proxy -f
          deployments/sdm-proxy/values.test.yaml | kubectl apply
          --dry-run=client -f -'
        language: system
        pass_filenames: false
    -   id: upgrade-client
        name: Helm upgrade | client
        entry: /bin/bash -c 'helm template deployments/sdm-client -f
          deployments/sdm-client/values.test.yaml | kubectl apply
          --dry-run=client -f -'
        language: system
        pass_filenames: false

    # Check failure paths
    -   id: template-relay-no-auth-failure
        name: Helm template | no auth fail | relay
        entry: /bin/bash -c '! helm template deployments/sdm-relay'
        language: system
        pass_filenames: false
    -   id: template-proxy-no-auth-failure
        name: Helm template | no auth fail | proxy
        entry: /bin/bash -c '! helm template deployments/sdm-proxy'
        language: system
        pass_filenames: false
    -   id: template-client-no-auth-failure
        name: Helm template | no auth fail | client
        entry: /bin/bash -c '! helm template deployments/sdm-client'
        language: system
        pass_filenames: false
    -   id: template-proxy-invalid-tls-failure
        name: Helm template | no tlsSecretName when tlsSource=file | proxy
        entry: /bin/bash -c '! helm template deployments/sdm-proxy -f
          deployments/sdm-proxy/values.test.yaml --set
          strongdm.service.tlsSource=file'
        language: system
        pass_filenames: false
    -   id: template-relay-missing-healthcheck-username
        name: Helm template | no healthcheck username when using Identity Aliases | relay
        entry: /bin/bash -c '! helm template deployments/sdm-relay -f deployments/sdm-relay/values.test.yaml --set strongdm.discoveryUsername=foobar --set strongdm.autoRegisterCluster.identitySetName=foobar'
        language: system
        pass_filenames: false
    -   id: template-relay-missing-discovery-username
        name: Helm template | no discovery username when using Identity Aliases | relay
        entry: /bin/bash -c '! helm template deployments/sdm-relay -f deployments/sdm-relay/values.test.yaml --set strongdm.healthcheckUsername=foobar --set strongdm.autoRegisterCluster.identitySetName=foobar'
        language: system
        pass_filenames: false

    # Check version pin paths
    -   id: template-tag-pin-relay
        name: Helm template | tag pin should disable SDM_DISABLE_UPDATE | relay
        entry: >
          bash -c '[[ "$(helm template deployments/sdm-relay -f deployments/sdm-relay/values.test.yaml
          --set strongdm.image.tag=100.10.0
          | yq -r ". | select(.kind == \"ConfigMap\") | .data.SDM_DISABLE_UPDATE")"
          == "true" ]]'
        language: system
        pass_filenames: false
    -   id: template-tag-pin-proxy
        name: Helm template | tag pin should disable SDM_DISABLE_UPDATE | proxy
        entry: >
          bash -c '[[ "$(helm template deployments/sdm-proxy -f deployments/sdm-proxy/values.test.yaml
          --set strongdm.image.tag=100.10.0
          | yq -r ". | select(.kind == \"ConfigMap\") | .data.SDM_DISABLE_UPDATE")"
          == "true" ]]'
        language: system
        pass_filenames: false
    -   id: template-digest-pin-relay
        name: Helm template | digest pin should disable SDM_DISABLE_UPDATE |
          relay
        entry: >
          bash -c '[[ "$(helm template deployments/sdm-relay -f deployments/sdm-relay/values.test.yaml
          --set strongdm.image.digest=aaa
          | yq -r ". | select(.kind == \"ConfigMap\") | .data.SDM_DISABLE_UPDATE")"
          == "true" ]]'
        language: system
        pass_filenames: false
    -   id: template-digest-pin-proxy
        name: Helm template | digest pin should disable SDM_DISABLE_UPDATE |
          proxy
        entry: >
          bash -c '[[ "$(helm template deployments/sdm-proxy -f deployments/sdm-proxy/values.test.yaml
          --set strongdm.image.digest=aaa
          | yq -r ". | select(.kind == \"ConfigMap\") | .data.SDM_DISABLE_UPDATE")"
          == "true" ]]'
        language: system
        pass_filenames: false

-   repo: https://github.com/losisin/helm-values-schema-json
    rev: v2.2.0
    hooks:
    -   id: helm-schema
        name: helm-schema | relay
        args: ["-input", "deployments/sdm-relay/values.yaml", "-output", "deployments/sdm-relay/values.schema.json"]
    -   id: helm-schema
        name: helm-schema | proxy
        args: ["-input", "deployments/sdm-proxy/values.yaml", "-output", "deployments/sdm-proxy/values.schema.json"]
    -   id: helm-schema
        name: helm-schema | client
        args: ["-input", "deployments/sdm-client/values.yaml", "-output", "deployments/sdm-client/values.schema.json"]
