apiVersion: v2
name: sdm-relay
kubeVersion: ">= 1.16.0-0"
version: 2.3.4
description: StrongDM Relay
type: application
icon: https://raw.githubusercontent.com/strongdm/charts/main/sdm_icon.png
home: https://github.com/strongdm/charts
maintainers:
  - name: StrongDM
    email: k8s+sdm@strongdm.com
sources:
  - https://github.com/strongdm/charts/tree/main/deployments/sdm-relay
keywords:
  - strongdm
  - sdm
