agents:
  - infra-mgmt-services
  - releases

steps:
  - label: ":helm: package"
    if: build.branch == "main" && build.author.email != "infra+sdmrelease@strongdm.com"
    command: .buildkite/package.sh
