---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "strongdm.name" . }}-config
  namespace: {{ include "strongdm.namespace" . }}
  annotations:
    {{- include "strongdm.annotations" . | nindent 4 }}
  labels:
    {{- include "strongdm.labels" . | nindent 4 }}
data:
  SDM_APP_DOMAIN: {{ .Values.strongdm.config.appDomain | default (printf "app.%s" .Values.strongdm.config.domain) }}
  SDM_DISABLE_UPDATE: {{ (or .Values.strongdm.config.disableAutoUpdate (not (empty .Values.strongdm.image.digest)) (ne .Values.strongdm.image.tag "latest")) | quote }}
  SDM_MAINTENANCE_WINDOW_START: {{ .Values.strongdm.config.maintenanceWindowStart | quote }}
  SDM_VERBOSE: {{ .Values.strongdm.config.verboseLogs | quote }}
  SDM_DOCKERIZED: {{ eq .Values.strongdm.config.queryLogs.storage "stdout" | ternary "stderr" "true" | quote }}
  SDM_RELAY_LOG_FORMAT: {{ .Values.strongdm.config.queryLogs.format }}
  SDM_RELAY_LOG_STORAGE: {{ .Values.strongdm.config.queryLogs.storage }}
  SDM_RELAY_LOG_ENCRYPTION: {{ .Values.strongdm.config.queryLogs.encryption }}
  SDM_ORCHESTRATOR_PROBES: :9090
  SDM_METRICS_LISTEN_ADDRESS: {{ .Values.strongdm.config.enableMetrics | ternary ":9999" "" }}
  {{- range $k, $v := .Values.strongdm.config.additionalEnvVars }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
