---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "strongdm.name" . }}
  namespace: {{ include "strongdm.namespace" . }}
  annotations:
    {{- include "strongdm.annotations" (merge (dict "addtl" .Values.strongdm.deployment.annotations) .) | nindent 4 }}
  labels:
    {{- include "strongdm.labels" (merge (dict "addtl" .Values.strongdm.deployment.labels) .) | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "strongdm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- include "strongdm.annotations" (merge (dict "addtl" .Values.strongdm.pod.annotations) .) | nindent 8 }}
      labels:
        {{- include "strongdm.labels" (merge (dict "addtl" .Values.strongdm.pod.labels) .) | nindent 8 }}
    spec:
      restartPolicy: Always
      {{- if or .Values.strongdm.serviceAccount.create .Values.strongdm.serviceAccount.name }}
      serviceAccountName: {{ .Values.strongdm.serviceAccount.create | ternary .Release.Name .Values.strongdm.serviceAccount.name }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      nodeSelectors:
        {{- with .Values.strongdm.deployment.nodeSelector }}
        {{- toYaml . | nindent 2 }}
        {{- end }}
      tolerations:
        {{- with .Values.strongdm.deployment.tolerations }}
        {{- toYaml . | nindent 2 }}
        {{- end }}
      containers:
        - name: sdm
          image: {{ template "strongdm.imageURI" . }}
          imagePullPolicy: {{ .Values.strongdm.image.pullPolicy }}
          {{- include "strongdm.resources" (dict "resources" .Values.strongdm.pod.resources) | nindent 10 }}
          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  containerName: sdm
                  resource: requests.cpu
                  divisor: "1"
            - name: SDM_RELAY_TOKEN
              valueFrom:
                secretKeyRef:
                  key: SDM_RELAY_TOKEN
                  name: {{ .Values.strongdm.autoCreateNode.enabled | ternary (printf "%s-relay-token" .Release.Name) (default (printf "%s-secrets" .Release.Name) .Values.strongdm.auth.secretName) }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
          ports:
            - name: healthcheck
              containerPort: 9090
              protocol: TCP
            {{- if .Values.strongdm.gateway.enabled }}
            - name: gateway
              containerPort: {{ .Values.strongdm.gateway.containerPort }}
              protocol: TCP
            {{- end }}
            {{- if .Values.strongdm.config.enableMetrics }}
            - name: metrics
              containerPort: 9999
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: /liveness
              port: 9090
            initialDelaySeconds: 25
            timeoutSeconds: 10
            periodSeconds: 15
            failureThreshold: 5
