{{- if not .Values.strongdm.auth.secretName }}
{{- if not (or .Values.strongdm.auth.adminToken .Values.strongdm.auth.relayToken) }}
{{- fail "one of @strongdm.auth.relayToken or @strongdm.auth.adminToken must be set when when @strongdm.auth.secretName is not provided." }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "strongdm.name" . }}-secrets
  namespace: {{ include "strongdm.namespace" . }}
  annotations:
    {{- include "strongdm.annotations" . | nindent 4 }}
  labels:
    {{- include "strongdm.labels" . | nindent 4 }}
type: Opaque
data:
  SDM_RELAY_TOKEN: {{ .Values.strongdm.auth.relayToken | b64enc }}
  SDM_ADMIN_TOKEN: {{ .Values.strongdm.auth.adminToken | b64enc }}
{{- end }}
