{{- if .Values.strongdm.gateway.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "strongdm.name" . }}
  namespace: {{ include "strongdm.namespace" . }}
  annotations:
    {{- include "strongdm.annotations" (merge (dict "addtl" .Values.strongdm.gateway.service.annotations) .) | nindent 4 }}
  labels:
    {{- include "strongdm.labels" (merge (dict "addtl" .Values.strongdm.gateway.service.labels) .) | nindent 4 }}
spec:
  type: {{ .Values.strongdm.gateway.service.type }}
  loadBalancerIP: {{ .Values.strongdm.gateway.service.loadBalancerIP }}
  selector:
     {{- include "strongdm.selectorLabels" . | nindent 4 }}
  ports:
    - name: sdm
      port: {{ .Values.strongdm.gateway.listenPort }}
      targetPort: {{ .Values.strongdm.gateway.containerPort }}
      nodePort: {{ .Values.strongdm.gateway.service.nodePort }}
{{- end }}
